version: '3'

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthy_food
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      sh -c "psql -U postgres -d healthy_food -c 'CREATE EXTENSION IF NOT EXISTS vector;' &&
             psql -U postgres -d healthy_food -c 'CREATE INDEX IF NOT EXISTS post_product_embeddings_idx ON post_product USING hnsw (embeddings vector_cosine_ops);'"

  be:
    build:
      context: ./be
    command: >
      bash -c "
      /wait-for-it.sh db:5432 -t 10 &&
      python manage.py migrate &&
      gunicorn config.wsgi --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=healthy_food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - be

volumes:
  pgdata: