version: '3'

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthy_food
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  be:
    build:
      context: ./be
    command: >
      bash -c "
      python manage.py migrate &&
      gunicorn config.wsgi --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=healthy_food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - be

volumes:
  pgdata: