# Generated by Django 3.2.16 on 2024-04-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu',
            new_name='product',
        ),
    ]
