# Generated by Django 5.0.4 on 2024-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_seller_remove_orderitem_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='seller_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user_id',
            field=models.CharField(max_length=250),
        ),
    ]
