# Generated by Django 5.0.4 on 2024-04-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_seller_products_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.Seller')),

            ],
        ),
    ]
