# Generated by Django 5.0.4 on 2024-04-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_seller_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='SellerProduct',
        ),
    ]
